# Generated by Django 4.2.7 on 2026-01-09 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, help_text='Unique identifier for idempotency', max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('LEDGER_TRANSACTION_CREATED', 'Ledger Transaction Created'), ('PAYOUT_CREATED', 'Payout Created'), ('PAYOUT_PROCESSING', 'Payout Processing'), ('PAYOUT_COMPLETED', 'Payout Completed'), ('PAYOUT_FAILED', 'Payout Failed'), ('ACCOUNT_BALANCE_UPDATED', 'Account Balance Updated')], db_index=True, max_length=100)),
                ('aggregate_id', models.CharField(db_index=True, help_text='ID of the aggregate root (e.g., transaction_id, payout_id)', max_length=255)),
                ('aggregate_type', models.CharField(db_index=True, help_text='Type of aggregate (e.g., Transaction, Payout)', max_length=100)),
                ('event_data', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sequence_number', models.BigIntegerField(db_index=True, help_text='Monotonically increasing sequence number for ordering', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['event_id'], name='events_event_i_3912d3_idx'), models.Index(fields=['event_type', 'created_at'], name='events_event_t_9f6b23_idx'), models.Index(fields=['aggregate_type', 'aggregate_id', 'created_at'], name='events_aggrega_9c34e9_idx'), models.Index(fields=['sequence_number'], name='events_sequenc_9cbf2b_idx'), models.Index(fields=['created_at'], name='events_created_9e2206_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('event_id', ''), _negated=True), name='event_id_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('sequence_number__gt', 0)), name='sequence_number_positive'),
        ),
    ]
