# Generated by Django 4.2.7 on 2026-01-09 19:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_account', models.CharField(db_index=True, max_length=255)),
                ('payout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='payouts.payout')),
            ],
            options={
                'db_table': 'payout_summaries',
                'indexes': [models.Index(fields=['status', 'created_at'], name='payout_summ_status_161972_idx'), models.Index(fields=['recipient_account', 'created_at'], name='payout_summ_recipie_13a7d6_idx'), models.Index(fields=['created_at'], name='payout_summ_created_fccc43_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransactionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('entry_count', models.IntegerField()),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='ledger.transaction')),
            ],
            options={
                'db_table': 'ledger_transaction_summaries',
                'indexes': [models.Index(fields=['status', 'created_at'], name='ledger_tran_status_11f464_idx'), models.Index(fields=['created_at'], name='ledger_tran_created_aa3c0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('last_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_event_sequence', models.BigIntegerField(default=0, help_text='Sequence number of last processed event')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='ledger.account')),
            ],
            options={
                'db_table': 'account_balances',
                'indexes': [models.Index(fields=['account'], name='account_bal_account_1ae445_idx'), models.Index(fields=['last_updated_at'], name='account_bal_last_up_5747b8_idx')],
            },
        ),
    ]
