# Generated by Django 4.2.7 on 2026-01-09 19:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key to ensure exactly-once execution', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('recipient_account', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('ledger_transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('external_payout_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'payouts',
            },
        ),
        migrations.CreateModel(
            name='PayoutEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('PROCESSING_STARTED', 'Processing Started'), ('LEDGER_ENTRY_CREATED', 'Ledger Entry Created'), ('EXTERNAL_PAYOUT_INITIATED', 'External Payout Initiated'), ('EXTERNAL_PAYOUT_COMPLETED', 'External Payout Completed'), ('EXTERNAL_PAYOUT_FAILED', 'External Payout Failed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRY', 'Retry')], db_index=True, max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payouts.payout')),
            ],
            options={
                'db_table': 'payout_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['idempotency_key'], name='payouts_idempot_9843c4_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'created_at'], name='payouts_status_ef59be_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['ledger_transaction_id'], name='payouts_ledger__a9b3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['external_payout_id'], name='payouts_externa_1774b9_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['created_at'], name='payouts_created_1441ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(check=models.Q(('idempotency_key', ''), _negated=True), name='idempotency_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='payout_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='payoutevent',
            index=models.Index(fields=['payout', 'created_at'], name='payout_even_payout__71ff32_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutevent',
            index=models.Index(fields=['event_type', 'created_at'], name='payout_even_event_t_2cb01c_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutevent',
            index=models.Index(fields=['created_at'], name='payout_even_created_3ba868_idx'),
        ),
    ]
